"""GPU-accelerated CMIknn for PCMCI+ (torch/CUDA).

Two GPU test variants, both drop-in tigramite CondIndTest subclasses:

  cmiknn-gpu        per-call GPU KSG conditional-MI (validated bit-exact vs CPU).
  cmiknn-gpu-batch  the SAME estimator, but the whole permutation null (all
                    sig_samples shuffles) is computed in ONE batched GPU pass —
                    this is what actually saturates the GPU. Permutations are
                    generated by tigramite's exact restricted-permutation scheme,
                    so the null is correct; only the CMI arithmetic moves to CUDA.

Validate before trusting causal output:
    python tools/cmi_gpu.py --validate
"""

from __future__ import annotations

import numpy as np

try:
    import torch
    _DEV = "cuda" if torch.cuda.is_available() else "cpu"
except Exception:  # noqa: BLE001
    torch, _DEV = None, "cpu"


def _ranks(array):
    A = torch.as_tensor(np.asarray(array, dtype=np.float32), device=_DEV)
    return A.argsort(dim=-1).argsort(dim=-1).float()          # rank-transform each row


def _cheb_fixed(A, rows):
    """Pairwise Chebyshev distance (T,T) over a fixed set of rows."""
    T = A.shape[1]
    if len(rows) == 0:
        return torch.zeros((T, T), device=_DEV)
    X = A[rows].T                                            # (T, r)
    return (X.unsqueeze(1) - X.unsqueeze(0)).abs().amax(dim=2)


def ksg_cmi_gpu(array, xyz, knn=0.1):
    """Single KSG conditional-MI on the GPU. array: (D,T); xyz: 0=X,1=Y,2=Z."""
    A = _ranks(array)
    D, T = A.shape
    k = max(1, int(round(knn * T))) if knn < 1 else int(knn)
    xyz = np.asarray(xyz)
    xz = np.where((xyz == 0) | (xyz == 2))[0]
    yz = np.where((xyz == 1) | (xyz == 2))[0]
    z = np.where(xyz == 2)[0]
    eps = _cheb_fixed(A, np.arange(D)).kthvalue(k + 1, dim=1).values
    def cnt(rows):
        d = _cheb_fixed(A, rows)
        return ((d < eps.unsqueeze(1)).sum(1) - 1).clamp(min=0).float()
    dg = torch.special.digamma
    val = dg(torch.tensor(float(k), device=_DEV)) + \
        (dg(cnt(z) + 1) - dg(cnt(xz) + 1) - dg(cnt(yz) + 1)).mean()
    return float(val.detach().cpu())


def batched_null_cmi(array, xyz, perms, knn=0.1, permute="Y", chunk=256):
    """All permutation-null CMIs in batched GPU passes. perms: (B,T) index arrays
    that permute the X (or Y) rows; the other distances are fixed."""
    A = _ranks(array)
    D, T = A.shape
    k = max(1, int(round(knn * T))) if knn < 1 else int(knn)
    xyz = np.asarray(xyz)
    Xr, Yr, Zr = (np.where(xyz == v)[0] for v in (0, 1, 2))
    XZ, YZ = np.union1d(Xr, Zr), np.union1d(Yr, Zr)
    prows = list(Xr if permute == "X" else Yr)              # permuted rows
    def fixed(rows):
        return _cheb_fixed(A, [r for r in rows if r not in prows])
    d_fix_joint, d_fix_xz, d_fix_yz = fixed(range(D)), fixed(XZ), fixed(YZ)
    d_fix_z = _cheb_fixed(A, Zr)                            # z never contains the permuted var
    perm_in_xz = permute == "X"                             # which subspace the permuted var sits in
    Aperm = A[prows]                                        # (P,T)
    dg = torch.special.digamma
    psik = dg(torch.tensor(float(k), device=_DEV))
    out = []
    P = torch.as_tensor(np.asarray(perms), device=_DEV, dtype=torch.long)  # (B,T)
    for s in range(0, P.shape[0], chunk):
        idx = P[s:s + chunk]                               # (C,T)
        C = idx.shape[0]
        ap = Aperm[:, idx]                                 # (P,C,T)
        d_perm = torch.zeros((C, T, T), device=_DEV)
        for p in range(len(prows)):
            x = ap[p]                                      # (C,T)
            d_perm = torch.maximum(d_perm, (x.unsqueeze(2) - x.unsqueeze(1)).abs())
        d_joint = torch.maximum(d_perm, d_fix_joint)       # (C,T,T)
        eps = d_joint.kthvalue(k + 1, dim=2).values        # (C,T)
        epsb = eps.unsqueeze(2)
        def cnt(d_chunked):
            return ((d_chunked < epsb).sum(2) - 1).clamp(min=0).float()  # (C,T)
        d_xz = torch.maximum(d_perm, d_fix_xz) if perm_in_xz else d_fix_xz.unsqueeze(0)
        d_yz = d_fix_yz.unsqueeze(0) if perm_in_xz else torch.maximum(d_perm, d_fix_yz)
        nxz, nyz = cnt(d_xz), cnt(d_yz)
        nz = cnt(d_fix_z.unsqueeze(0))
        cmi = psik + (dg(nz + 1) - dg(nxz + 1) - dg(nyz + 1)).mean(dim=1)  # (C,)
        out.append(cmi.detach().cpu().numpy())
        del d_perm, d_joint, d_xz, d_yz
    return np.concatenate(out)


def _make_class(batched: bool):
    from tigramite.independence_tests.cmiknn import CMIknn
    from scipy import spatial

    class CMIknnGPU(CMIknn):
        def get_dependence_measure(self, array, xyz):
            return ksg_cmi_gpu(array, xyz, knn=self.knn)

        if batched:
            def get_shuffle_significance(self, array, xyz, value,
                                         return_null_dist=False, data_type=None):
                dim, T = array.shape
                z_idx = np.where(xyz == 2)[0]
                if len(z_idx) == 0 or self.shuffle_neighbors >= T:
                    return super().get_shuffle_significance(array, xyz, value,
                                                            return_null_dist, data_type)
                z_array = array[z_idx, :].copy()
                if self.transform == "ranks":
                    z_array = z_array.argsort(axis=1).argsort(axis=1).astype(np.float64)
                z_array = z_array.T
                neighbors = spatial.cKDTree(z_array).query(
                    z_array, k=self.shuffle_neighbors, p=np.inf, eps=0.)[1].astype(np.int32)
                perms = np.empty((self.sig_samples, T), dtype=np.int64)
                for sam in range(self.sig_samples):
                    order = self.random_state.permutation(T).astype(np.int32)
                    for i in range(len(neighbors)):
                        self.random_state.shuffle(neighbors[i])
                    perms[sam] = self.get_restricted_permutation(
                        T=T, shuffle_neighbors=self.shuffle_neighbors,
                        neighbors=neighbors, order=order)
                null_dist = batched_null_cmi(array, xyz, perms, knn=self.knn,
                                             permute=self.permute)
                pval = (null_dist >= value).mean()
                return (pval, null_dist) if return_null_dist else pval

    return CMIknnGPU


def make_cmiknn_gpu(batched: bool = False, sig_samples: int = 250):
    cls = _make_class(batched)
    # batched => bump permutations (more stats + more GPU work); per-call keep modest.
    return cls(significance="shuffle_test", knn=0.1, shuffle_neighbors=5,
               transform="ranks", sig_blocklength=1, workers=1, sig_samples=sig_samples)


def _validate():
    import time
    from tigramite.independence_tests.cmiknn import CMIknn
    rng = np.random.default_rng(0); T = 603
    z = rng.normal(size=T); x = 0.7 * z + rng.normal(size=T)
    y = 0.6 * x + 0.5 * z + rng.normal(size=T); indep = rng.normal(size=T)
    cpu = CMIknn(significance="shuffle_test", knn=0.1, shuffle_neighbors=5,
                 transform="ranks", sig_blocklength=1, workers=1, sig_samples=250)
    gpu = make_cmiknn_gpu(batched=True, sig_samples=250)
    print(f"device: {_DEV}")
    for name, arr, xyz in [("X;Y|Z (true)", np.vstack([x, y, z]), np.array([0, 1, 2])),
                           ("X;indep|Z (null)", np.vstack([x, indep, z]), np.array([0, 1, 2]))]:
        v = gpu.get_dependence_measure(arr, xyz)
        t0 = time.time(); pg = gpu.get_shuffle_significance(arr, xyz, v); tg = time.time() - t0
        t0 = time.time(); pc = cpu.get_shuffle_significance(arr, xyz, cpu.get_dependence_measure(arr, xyz)); tc = time.time() - t0
        print(f"  {name:18}  p(GPU-batch)={pg:.3f} [{tg:.2f}s]  p(CPU)={pc:.3f} [{tc:.2f}s]  "
              f"speedup {tc/max(tg,1e-9):.0f}x")


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(); ap.add_argument("--validate", action="store_true")
    if ap.parse_args().validate:
        _validate()
